/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react';
import { useGLTF, useCursor } from '@react-three/drei';
import { ChartInScene } from './Chart';
import { TowelieAnim } from './Towelie';

export function TokenBackground2(props) {
  const [hovered, setHovered] = useState(false);
  useCursor(hovered); // 👈 sets cursor: pointer when hovered

  const { nodes, materials } = useGLTF('/models/mr_garrison4-opt.glb');
  return (
    <group {...props} dispose={null} scale={35} position-y={-150}>
      <TowelieAnim />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.skin}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.299}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.purple}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.707}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.skin}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.71}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.skin}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.749}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.eye}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.731}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials.eye1}
        position={[-6.407, 5.08, 0.846]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.beard}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.707}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.beard}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.295}
      />
      <group position={[-6.421, 5.098, 0.777]} rotation={[0.247, 0.191, 0.281]} scale={0.656}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials.hat1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials.hat2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.black}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.704}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.black}
        position={[-6.421, 5.098, 0.777]}
        rotation={[0.247, 0.191, 0.281]}
        scale={0.707}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['skin.001']}
        position={[-4.972, 6.091, 0.145]}
        scale={0.392}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['skin.001']}
        position={[-6.115, 6.258, 0.209]}
        rotation={[Math.PI / 2, 0.158, 0]}
        scale={0.113}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.hair}
        position={[-4.977, 6.243, -0.911]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.hair}
        position={[-5.174, 6.519, 1.176]}
        rotation={[Math.PI / 2, 0, 0.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.black}
        position={[-5.378, 6.108, 1.301]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.352, 0.242, 0.242]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert.geometry}
        material={materials.black}
        position={[-5.23, 6.886, 0.954]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert001.geometry}
        material={materials.black}
        position={[-5.23, 5.329, 0.954]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={materials.eye1}
        position={[-5.129, 6.109, 1.314]}
        rotation={[1.061, -0.273, 0.161]}
        scale={0.09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials['skin.001']}
        position={[-4.972, 5.683, 1.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={materials.eye}
        position={[-5.194, 6.212, 1.143]}
        rotation={[-0.252, 0.021, -0.782]}
        scale={0.782}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.black}
        position={[-4.992, 5.704, 1.304]}
        rotation={[Math.PI / 2, -0.698, 0]}
        scale={-0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials.green1}
        position={[-4.971, 4.055, -0.084]}
        scale={[0.683, 0.653, 0.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials.black}
        position={[-4.971, 4.055, -0.175]}
        scale={[0.683, 0.653, 0.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials.green2}
        position={[-4.977, 2.776, -0.183]}
        scale={[1.059, 1.068, 1.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials.shoes}
        position={[-4.546, 0.531, -0.334]}
        scale={0.836}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.green1}
        position={[-5.694, 5.021, -0.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials['skin.001']}
        position={[-3.921, 3.426, -0.157]}
        rotation={[-0.158, 0.614, 0.006]}
        scale={0.198}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials.black}
        position={[-5.167, 4.055, -0.175]}
        scale={[0.683, 0.653, 0.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials.hair}
        position={[-4.977, 2.849, 0.526]}
        rotation={[1.742, 0, 0]}
        scale={0.156}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials.shoes}
        position={[-4.977, 2.849, 0.526]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials.black}
        position={[-4.971, 2.033, -0.746]}
        scale={[0.683, 0.653, 0.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.black}
        position={[-4.065, 4.03, 0.037]}
        rotation={[0, -0.097, 0]}
        scale={[0.683, 0.653, 0.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials.black}
        position={[-4.078, 4.03, -0.404]}
        rotation={[0, -0.097, -Math.PI]}
        scale={[-0.683, -0.653, -0.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials.black}
        position={[-5.779, 4.03, 0.037]}
        rotation={[0, -0.097, 0]}
        scale={[0.683, 0.653, 0.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials.black}
        position={[-5.779, 4.03, -0.416]}
        rotation={[0, -0.097, -Math.PI]}
        scale={[-0.683, -0.653, -0.683]}
      />
      <group position={[-0.033, 0.413, -0.075]} scale={3.594}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.class1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_2.geometry}
          material={materials.class2}
        />
      </group>
      <group position={[-0.033, 4.275, -3.669]} scale={3.594}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_1.geometry}
          material={materials['class1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_2.geometry}
          material={materials.black}
        />
      </group>
      <group position={[-1.3, 5.275, -3.669]} scale={1.5}>
        <ChartInScene />
      </group>
      <group position={[3.023, 1.076, 0.411]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_1.geometry}
          material={materials.class3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_2.geometry}
          material={materials.black}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials.hat2}
        position={[4.686, 3.517, 0.194]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials.beard}
        position={[4.686, 3.703, 0.194]}
      />
      <mesh
        className="hover:cursor-pointer"
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials.class5}
        position={[0.037, 8.484, -3.669]}
        rotation={[Math.PI / 2, 0, 0]}
        onClick={() => {
          window.open(
            'https://dexscreener.com/base/0x5a8e535a71cf042790c4ffefa502d554908ff72a',
            '_blank', // opens in new tab; use "_self" to redirect in same tab
          );
        }}
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mnkey.geometry}
        material={materials.mnkey}
        position={[4.323, 6.456, -3.638]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials.blue}
        position={[3.44, 7.202, -3.669]}
        rotation={[0, 0, -0.668]}
        scale={1.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials.blue}
        position={[5.438, 7.213, -3.669]}
        rotation={[0, 0, -2.443]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials.blue}
        position={[5.464, 4.748, -3.669]}
        rotation={[0, 0, 2.531]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials.blue}
        position={[3.438, 4.751, -3.669]}
        rotation={[0, 0, Math.PI / 4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Иллюстрация_без_названия_4.geometry}
        material={materials['Иллюстрация_без_названия 4']}
        position={[3.035, 3.2, 0.391]}
        rotation={[0, -0.336, 0]}
        scale={1.755}
      />
    </group>
  );
}

useGLTF.preload('/models/mr_garrison4-opt.glb');
